[pytest]
markers =
    ui: UI tests
    api: API tests
    smoke: Smoke tests
    negative: Negative tests
addopts = -v -s --alluredir=allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*